name: Image optimization

on: [push, pull_request]

jobs:
  general_image_workflow:
    uses: Karaka-Management/Karaka/.github/workflows/image.yml@develop
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
