name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  general_module_workflow:
    uses: Karaka-Management/Karaka/.github/workflows/module.yml@develop
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
